version: "3"

services:
  redis:
    image: redis:alpine
    container_name: auth-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/:/data
  app:
    image: hseungho/liberty52-auth-server:dev-0.0.2
    container_name: auth-app
    ports:
      - "8080:8080"
    depends_on:
      - redis