spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: rXFpqK8eUqJ82ZyD9rfo
            client-secret: Ty9IPlgQ1x
            redirect-uri: "http://13.125.49.218:8080/auth/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email, profile_image, mobile, name
            client-name: Naver
          kakao:
            client-id: 987480ac95238226d696d70c2ec06be4
            redirect-uri: "http://13.125.49.218:8080/auth/login/oauth2/code/{registrationId}" # http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
          google:
            client-id: 286791574239-9mnjn8fg1e0fsur237jnlqvp7r2qnu0o.apps.googleusercontent.com
            redirect-uri: "https://lb.liberty52.com/auth/login/oauth2/code/google" # http://localhost:8080/login/oauth2/code/kakao
            client-secret: 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
            scope: email, profile
          facebook:
            client-id: 961899354834644
            client-secret: 66fcb897079cc0517bd0eddf67ea941c
            redirect-uri: "https://lb.liberty52.com/auth/login/oauth2/code/facebook" # http://localhost:8080/login/oauth2/code/kakao
            scope: email, public_profile
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          facebook:
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large)
