server:
  port: 0

spring:
  profiles:
    include:
      - oauth-sample
  config:
    import:
      - classpath:eureka-config-sample.yml
      - classpath:aws-config-sample.yml
      - classpath:jwt-config.yml
  application:
    name: auth
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: on
      path: /h2-console

logging:
  level:
    root: info