server:
  port: 8080

spring:
  application:
    name: auth
  profiles:
    active: local
  config:
    import:
      - optional:configserver:http://54.180.92.188:8888/
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: on
      path: /h2-console
      settings:
        web-allow-others: true

  servlet:
    multipart:
      max-file-size: 10MB

  cloud:
    config:
      label: main

logging:
  level:
    root: info