server:
  port: 8080

spring:
  application:
    name: auth
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:http://a1a8630485e9e4831ad6b1e03d923edc-1731221295.us-west-2.elb.amazonaws.com:8888/
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: on
      path: /h2-console
  cloud:
    config:
      label: main

logging:
  level:
    root: info