spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 4ztKZv4VT0bZ98DHY20u
            client-secret: WMXU_SRbjM
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: email, profile_image, mobile
            client-name: Naver
          kakao:
            client-id: 54ee4f8d451940b768d25ac695fe625d
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}" # http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
          google:
            client-id: 531825395949-l08ihgbcsql6qv3iuqkh7bnrbomtuhac.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
          facebook:
            client-id: 192318016885022
            client-secret: 986bfd88ab50ae67a85eb8073e5d7b12
            scope: email, public_profile
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
