spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: rXFpqK8eUqJ82ZyD9rfo
            client-secret: Ty9IPlgQ1x
            redirect-uri: "http://13.125.49.218:8080/auth/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email, profile_image, mobile
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response