spring:
  config:
    import:
#      - classpath:kafka-config.yml
#      - classpath:db-config.yml
      - classpath:eureka-config.yml
      - classpath:aws-config.yml
  #      - classpath:kafka-topics.yml
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: auth