spring:
  application:
    name: auth
  profiles:
    active: local

  config:
    import:
      - optional:configserver:http://54.180.92.188:8888/
  cloud:
    config:
      label: main

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    root: info

server:
  port: 8080
