spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 4ztKZv4VT0bZ98DHY20u
            client-secret: WMXU_SRbjM
            redirect-uri: "http://localhost:8080/auth/login/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: email, profile_image, mobile
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response