spring:
  profiles:
    include:
      - oauth
  config:
    import:
#      - classpath:eureka-config.yml
      - classpath:aws-config-sample.yml
  application:
    name: auth
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: on
      path: /h2-console


jwt:
  secretKey: eqjUk3IihCy9ZUIsun7V2BKysTULbZxUlA8Zb6jAriWHEiNDnSeqjUk3IihCy9ZUIsun7V2BKysTULbZxUlA8Zb6jAriWHEiNDnSeqjUk3IihCy9ZUIsun7V2BKysTULbZxUlA8Zb6jAriWHEiNDnSeqjUk3IihCy9ZUIsun7V2BKysTULbZxUlA8Zb6jAriWHEiNDnSeqjUk3IihCy9ZUIsun7V2BKysTULbZxUlA8Zb6jAriWHEiNDnSeqjUk3IihCy9ZUIsun7V2BKysTULbZxUlA8Zb6jAriWHEiNDnS
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 3600000
    header: Authorization-refresh

logging:
  level:
    root: info