server:
  port: 8080

spring:
  application:
    name: auth
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:http://3.34.181.222:8888/
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: on
      path: /h2-console
  cloud:
    config:
      label: main
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    root: info