server:
  port: 8080

spring:
  application:
    name: auth
  profiles:
    active: prod
  config:
    import:
      - optional:configserver:http://3.34.181.222:8888/
      - classpath:aws-config-sample.yml
      - classpath:application-oauth-sample.yaml
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: on
      path: /h2-console
  cloud:
    config:
      label: main

logging:
  level:
    root: info

frontend:
  url: http://localhost:3000