server:
  port: 8081

spring:
  application:
    name: auth
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:http://config-server.liberty52.com:8888/
  cloud:
    config:
      label: main